[package]
name = "rojo"
version = "0.6.0-alpha.1"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
description = "Enables professional-grade development tools for Roblox developers"
license = "MPL-2.0"
homepage = "https://rojo.space"
documentation = "https://rojo.space/docs"
repository = "https://github.com/rojo-rbx/rojo"
readme = "README.md"
edition = "2018"

exclude = [
    "/plugin/**",
    "/test-projects/**",
]

[features]
default = []

# Turn on support for specifying glob ignore path rules in the project format.
unstable_glob_ignore_paths = []

# Turn on the server half of Rojo's unstable two-way sync feature.
unstable_two_way_sync = []

# Enable this feature to live-reload assets from the web UI.
dev_live_assets = []

[workspace]
members = [
    "rojo-test",
    "rojo-insta-ext",
    "clibrojo",
    "vfs",
]

default-members = [
    ".",
    "rojo-test",
    "rojo-insta-ext",
    "vfs",
]

[lib]
name = "librojo"
path = "src/lib.rs"

[[bin]]
name = "rojo"
path = "src/bin.rs"

[[bench]]
name = "build"
harness = false

[dependencies]
crossbeam-channel = "0.4.0"
csv = "1.1.1"
env_logger = "0.7.1"
futures = "0.1.29"
globset = "0.4.4"
humantime = "1.3.0"
hyper = "0.14.10"
jod-thread = "0.1.0"
lazy_static = "1.4.0"
log = "0.4.8"
maplit = "1.0.1"
notify = "4.0.14"
rbx_binary = "0.5.0"
rbx_dom_weak = "1.10.1"
rbx_reflection = "3.3.408"
rbx_xml = "0.11.3"
regex = "1.3.1"
reqwest = "0.9.20"
ritz = "0.1.0"
rlua = "0.17.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
snafu = "0.6.0"
structopt = "0.3.5"
termcolor = "1.0.5"
uuid = { version = "0.8.1", features = ["v4", "serde"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.6.2"

[dev-dependencies]
rojo-insta-ext = { path = "rojo-insta-ext" }

criterion = "0.3"
insta = { version = "0.12.0", features = ["redactions"] }
lazy_static = "1.2"
paste = "0.1"
pretty_assertions = "0.6.1"
serde_yaml = "0.8.9"
tempfile = "3.0"
tokio = "0.1.22"
walkdir = "2.1"
